name: cron

on:
  schedule:
    - cron: '31 10,17 1-25 12 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        env:
          LEADERBOARD_ID: ${{ secrets.LEADERBOARD_ID }}
          SESSION_ID: ${{ secrets.SESSION_ID }}
          SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        run: python leaderboard.py
